### ISSUE TITLE
Error during npm start

### ISSUE THREAD

**Issue by paillave** [strongloop/loopback4-example-getting-started#13]
It appears that the getting start example fails to start.
Here is the error I get when I run npm start from ubuntu 17.10:
paillave@paillave-VC60:~/Documents/loopback4-example-getting-started$ npm start

> loopback4-example-getting-started@1.0.0 start /home/paillave/Documents/loopback4-example-getting-started
> npm run build && node .

> loopback4-example-getting-started@1.0.0 build /home/paillave/Documents/loopback4-example-getting-started
> lb-tsc && lb-tslint

module.js:557
    throw err;
    ^

Error: Cannot find module '/home/paillave/Documents/loopback4-example-getting-started'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:618:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! loopback4-example-getting-started@1.0.0 start: `npm run build && node .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the loopback4-example-getting-started@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/paillave/.npm/_logs/2017-12-17T12_36_21_630Z-debug.log

**Comment by fastspeeed** [comment]
modify "main": "index.js" to "main": "./dist/index.js" in package.json

**Comment by shimks** [comment]
Thanks for pointing this issue out! The issue was that our `.gitignore` ignored the `index.js` at root level, which is supposed to start the application. I'll be making a PR to fix this issue.

**Comment by shimks** [comment]
@paillave In the mean time, you can add in this file as `index.js` to the root level: 
```
const nodeMajorVersion = +process.versions.node.split(".")[0];
const dist = nodeMajorVersion >= 7 ? "./dist" : "./dist6";

const application = (module.exports = require(dist));

if (require.main === module) {
  // Run the application
  application.main();
}

```

**Comment by raymondfeng** [comment]
It will be fixed by https://github.com/strongloop/loopback4-example-getting-started/pull/16
