### ISSUE TITLE
Post method getting end point not found error

### ISSUE THREAD

**Issue by conqsys** [strongloop/loopback4-example-getting-started#8]
[Screeshot of the error](https://ibb.co/kf5E3R)

Also getting this  error TS6133: 'post' is declared but its value is never read

**Comment by dhmlau** [comment]
@conqsys , from the screenshot, you're trying to call a POST method for /user, and this endpoint does not exist in this example repo.  Could you please provide us a sample repo?

**Comment by conqsys** [comment]
dhmlau thanks for your response.

this error was because of cors was not enabled.

I need a help how can i gives table name for query it is taking model name same as table name.
can we have table name with different table name

**Comment by dhmlau** [comment]
You can specify the table name that maps to the model name by adding the options in `config\datasources.json`.  Please see: https://loopback.io/doc/en/lb3/Model-definition-JSON-file.html#data-source-specific-options

**Comment by conqsys** [comment]
i'm using loopback 4 with typescript and mssql

how can i call stored procedure


this is my datasource config

import { DataSourceConstructor} from '@loopback/repository';

export const db = new DataSourceConstructor({
  connector: 'mssql',
  host: '192.168.1.110',
  port: 1433,
  database: 'FastDryNew',
  password: 'sa$123',
  user: 'sa',
});

**Comment by dhmlau** [comment]
the `db` would be something like:
```
export const db = new DataSourceConstructor({
connector: 'mssql',
host: '192.168.1.110',
port: 1433,
database: 'FastDryNew',
password: 'sa$123',
user: 'sa',
options: {
 <<db type>>: {
    table: <<table name>>
 }
}
});
```

where `<<db type>>` is database name, e.g. mysql, db2, oracle,
and `<<table name>>` is the table name that corresponds to the model

**Comment by dhmlau** [comment]
@conqsys , just wanna check with you.. Is your problem resolved?

**Comment by dhmlau** [comment]
@conqsys , we believe your problem has been resolved.  If it still exists, feel free to reopen.  Thanks for using LoopBack 4!

**Comment by shashi97** [comment]
@dhmlau Thanks

I have a query that should be on discussion page but just asking here

I have completed my app in LB4 and the next phase production i run a command npm run build but its build in dist file with .map files i think that is not production build so what i need to do there is no proper documentation is available so i'm asking here

thanks in advance

**Comment by dhmlau** [comment]
@shashi97 , looks like you've opened this issue: https://github.com/strongloop/loopback4-example-getting-started/issues/10.
