### ISSUE TITLE
Only listening on localhost

### ISSUE THREAD

**Issue by StianOvrevage** [strongloop/loopback4-example-getting-started#9]
All of the LB4 examples I have used ends up with a server listening on only localhost, including this one. I see there are snippets of code on how to invoke servers and contexts with different configurations, but none of them are complete so I'm not able to glue them together without knowing a lot about how LB4 works already.

**Comment by shashi97** [comment]
Use this on your application.ts:
import { RestComponent, RestServer }
 from "@loopback/rest";

And write this function on your application.ts
  async start() {
    // get a singleton HTTP server instance
    const rest = await this.getServer(RestServer)
    rest.bind('rest.port').to(46001);  // you can give your port number
    rest.bind('rest.host').to("192.168.1.95"); // you can give your IP
    await super.start();
  }

**Comment by raymondfeng** [comment]
It will be fixed by https://github.com/strongloop/loopback-next/pull/765.
